---
- hosts: all
  become: yes
  become_user: root
  become_method: su
  become_flags: '-s /bin/sh'
  tasks:
    - name: Copy node_exporter systemd service file to server
      copy:
        src: node_exporter.service
        dest: /etc/systemd/system
        owner: root
        group: root
      register: file_copy


    - name: Start the node_exporter service
      systemd:
        name: node_exporter.service
        state: restarted
        enabled: yes
      when: file_copy is succeeded

